export default {
    "custom-header-text": "Tittel",
    "custom-subheader-text": "Undertittel",
    "custom-paragraph-text": "Tekst",
    "custom-description-list-data": "Data",
    "custom-field-adresse": "Adresse",
    "custom-field-boolean-data": "Ja/Nei (data)",
    "custom-field-boolean-text": "Ja/Nei (tekst)",
    "custom-field-count-data": "Antall (data)",
    "custom-field-data": "Data",
    "custom-field-kode": "Kode",
    "custom-field-kommunens-saksnummer": "Kommunens saksnummer",
    "custom-field-list-data": "Feltliste",
    "custom-field-part-navn": "Part navn",
    "custom-field-prosjekt": "Prosjekt",
    "custom-field-telefonnummer": "Telefonnummer",
    "custom-field-utfall-svar-status": "Utfall svar status",
    "custom-list-data": "Data",
    "custom-list-planlagte-loefteinnretninger": "Planlagte løfteinnretninger",
    "custom-list-vedlegg": "Vedlegg",
    "custom-table-ansvarsomraade": "Ansvarsområde",
    "custom-table-ansvarsrett-ansvarsomraade": "Ansvarsområde (ansvarsrett)",
    "custom-table-arbeidsplasser": "Arbeidsplasser",
    "custom-table-data": "Data",
    "custom-table-eiendom": "Eiendom",
    "custom-table-nabo-gjenboer-eiendom": "Nabo/gjenboer eiendom",
    "custom-table-omraaderisiko": "Områderisiko",
    "custom-table-part": "Part",
    "custom-table-part-gjennomfoeringsplan": "Part (gjennomføringsplan)",
    "custom-table-plan": "Plan",
    "custom-summation-arealdisponering": "Arealdisponering",
    "custom-summation-data": "Data",
    "custom-group-adkomst": "Adkomst",
    "custom-group-ansvarsrett-erklaeringer": "Ansvarsrettserklæringer",
    "custom-group-avloep": "Avløp",
    "custom-group-dispensasjon-oversikt": "Dispensasjonsoversikt",
    "custom-group-ettersending": "Ettersending",
    "custom-group-kontroll-ansvarsomraade": "Ansvarsområde (kontroll)",
    "custom-group-kontroll-erklaeringer": "Kontrollerklæringer",
    "custom-group-loefteinnretninger": "Løfteinnretninger",
    "custom-group-nabo-gjenboer-eiendom": "Nabo/gjenboer eiendom",
    "custom-group-overvann": "Overvann",
    "custom-group-rammebetingelser-krav-til-byggegrunn": "Krav til byggegrunn",
    "custom-group-rammebetingelser-tilknytninger": "Rammebetingelser tilknytninger",
    "custom-group-samsvar-ansvarsomraade": "Ansvarsområde (samsvar)",
    "custom-group-samsvar-erklaeringer": "Samsvarserklæringer",
    "custom-group-sjekklistekrav": "Sjekklistekrav",
    "custom-group-sjekklistekrav-header-text": "Sjekklistekrav (overskrift)",
    "custom-group-utfall-svar": "Utfall svar",
    "custom-group-utfall-svar-type": "Utfall svar type",
    "custom-group-vannforsyning": "Vannforsyning",
    "custom-group-vegtype-tillatelse": "Vegtype tillatelse",
    "custom-grouplist-ansvarsomraade-type": "Ansvarsområde",
    "custom-grouplist-ettersending": "Ettersending",
    "custom-grouplist-nabo-gjenboer-eiendom": "Nabo/gjenboer eiendom",
    "custom-grouplist-samsvar-ansvarsomraade": "Ansvarsområde (samsvar)",
    "custom-grouplist-sjekklistekrav": "Sjekklistekrav",
    "custom-grouplist-utfall-svar-type": "Utfall svar type",
    "custom-grouplist-utfall-svar": "Utfall svar",
    "custom-grouplist-vegtype-tillatelse": "Vegtype tillatelse",
    "custom-dispensasjon": "Dispensasjonssøknad",
    "custom-dispensasjonsvarsel": "Dispensasjonsvarsel",
    "custom-gjennomfoeringsplan": "Gjennomføringsplan",
    "custom-gjenpart-nabovarsel": "Gjenpart nabovarsel"
};
